# Mosquitto Configuration - SIKAP Development
# MQTT standard listener
listener 1883
protocol mqtt
allow_anonymous true

# MQTT over WebSocket (untuk frontend browser)
listener 9001
protocol websockets
allow_anonymous true

# Logging
log_dest stdout
log_type all

# Persistence
persistence true
persistence_location /mosquitto/data/
