"""add laporan table

Revision ID: 13491b3684cf
Revises: e7f7ef216f41
Create Date: 2026-04-05 01:36:02.368528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13491b3684cf'
down_revision = 'e7f7ef216f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laporan',
    sa.Column('id_laporan', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('filter_data', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("format IN ('pdf', 'excel')", name='ck_laporan_format_valid'),
    sa.CheckConstraint("jenis IN ('kelas', 'siswa', 'sekolah')", name='ck_laporan_jenis_valid'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id_user'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_laporan'),
    sa.UniqueConstraint('file_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laporan')
    # ### end Alembic commands ###
