"""add operasional and support tables

Revision ID: 66cbfbd60f7a
Revises: 13491b3684cf
Create Date: 2026-04-05 09:26:54.850169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cbfbd60f7a'
down_revision = '13491b3684cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sekolah_info',
    sa.Column('id_sekolah', sa.Integer(), nullable=False),
    sa.Column('nama_sekolah', sa.String(length=150), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('no_telp', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('foto_masjid_path', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_sekolah')
    )
    op.create_table('guru',
    sa.Column('id_guru', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('nip', sa.String(length=30), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('jabatan', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_guru'),
    sa.UniqueConstraint('id_user'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('jadwal_piket',
    sa.Column('id_jadwal', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('hari', sa.String(length=10), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_jadwal')
    )
    op.create_table('notifikasi',
    sa.Column('id_notifikasi', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=100), nullable=False),
    sa.Column('pesan', sa.Text(), nullable=False),
    sa.Column('tipe', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notifikasi')
    )
    op.create_table('password_reset_token',
    sa.Column('id_token', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_token'),
    sa.UniqueConstraint('token')
    )
    op.create_table('izin_pengajuan',
    sa.Column('id_izin', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('alasan', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('id_verifikator', sa.Integer(), nullable=True),
    sa.Column('catatan_verifikator', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id_siswa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_verifikator'], ['users.id_user'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_izin')
    )
    op.create_table('orangtua',
    sa.Column('id_ortu', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_siswa', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id_siswa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_ortu'),
    sa.UniqueConstraint('id_user')
    )
    op.create_table('sengketa_absensi',
    sa.Column('id_sengketa', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=False),
    sa.Column('id_sesi', sa.Integer(), nullable=False),
    sa.Column('alasan', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('id_verifikator', sa.Integer(), nullable=True),
    sa.Column('catatan_verifikator', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_sesi'], ['sesi_sholat.id_sesi'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id_siswa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_verifikator'], ['users.id_user'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_sengketa')
    )
    op.create_table('surat_peringatan',
    sa.Column('id_sp', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=False),
    sa.Column('sp_ke', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jenis', sa.String(length=10), nullable=False),
    sa.Column('status_kirim', sa.String(length=20), server_default='belum_kirim', nullable=True),
    sa.Column('id_pengirim', sa.Integer(), nullable=True),
    sa.Column('alasan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pengirim'], ['users.id_user'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id_siswa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surat_peringatan')
    op.drop_table('sengketa_absensi')
    op.drop_table('orangtua')
    op.drop_table('izin_pengajuan')
    op.drop_table('password_reset_token')
    op.drop_table('notifikasi')
    op.drop_table('jadwal_piket')
    op.drop_table('guru')
    op.drop_table('sekolah_info')
    # ### end Alembic commands ###
