"""Initial core schema

Revision ID: 9e997f33c9fd
Revises: 
Create Date: 2026-04-04 20:59:10.521295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e997f33c9fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perangkat',
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('nama_device', sa.String(length=100), nullable=False),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='offline', nullable=False),
    sa.Column('last_ping', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('online', 'offline')", name='ck_perangkat_status_valid'),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('status_absensi',
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('deskripsi', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('kode')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('no_telp', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'kepsek', 'wali_kelas', 'guru_piket', 'siswa', 'orangtua')", name='ck_users_role_valid'),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('waktu_sholat',
    sa.Column('id_waktu', sa.Integer(), nullable=False),
    sa.Column('nama_sholat', sa.String(length=20), nullable=False),
    sa.Column('waktu_adzan', sa.Time(), nullable=False),
    sa.Column('waktu_iqamah', sa.Time(), nullable=False),
    sa.Column('waktu_selesai', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id_waktu'),
    sa.UniqueConstraint('nama_sholat')
    )
    op.create_table('kelas',
    sa.Column('id_kelas', sa.Integer(), nullable=False),
    sa.Column('nama_kelas', sa.String(length=20), nullable=False),
    sa.Column('tingkat', sa.String(length=5), nullable=False),
    sa.Column('jurusan', sa.String(length=50), nullable=True),
    sa.Column('id_wali', sa.Integer(), nullable=True),
    sa.Column('tahun_ajaran', sa.String(length=10), nullable=False),
    sa.CheckConstraint("tingkat IN ('X', 'XI', 'XII')", name='ck_kelas_tingkat_valid'),
    sa.ForeignKeyConstraint(['id_wali'], ['users.id_user'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_kelas'),
    sa.UniqueConstraint('nama_kelas', 'tahun_ajaran', name='uq_kelas_nama_tahun_ajaran')
    )
    op.create_table('sesi_sholat',
    sa.Column('id_sesi', sa.Integer(), nullable=False),
    sa.Column('id_waktu', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='aktif', nullable=False),
    sa.CheckConstraint("status IN ('aktif', 'selesai')", name='ck_sesi_sholat_status_valid'),
    sa.ForeignKeyConstraint(['id_waktu'], ['waktu_sholat.id_waktu'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sesi'),
    sa.UniqueConstraint('id_waktu', 'tanggal', name='uq_sesi_sholat_id_waktu_tanggal')
    )
    op.create_table('siswa',
    sa.Column('id_siswa', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nisn', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=10), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('no_telp_ortu', sa.String(length=20), nullable=True),
    sa.Column('id_card', sa.String(length=50), nullable=True),
    sa.Column('id_kelas', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("jenis_kelamin IS NULL OR jenis_kelamin IN ('L', 'P')", name='ck_siswa_jenis_kelamin_valid'),
    sa.ForeignKeyConstraint(['id_kelas'], ['kelas.id_kelas'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_siswa'),
    sa.UniqueConstraint('id_card'),
    sa.UniqueConstraint('id_user'),
    sa.UniqueConstraint('nisn')
    )
    op.create_table('absensi',
    sa.Column('id_absensi', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=False),
    sa.Column('id_sesi', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=True),
    sa.Column('id_verifikator', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.CheckConstraint("status IN ('tepat_waktu', 'terlambat', 'alpha', 'haid', 'izin', 'sakit')", name='ck_absensi_status_valid'),
    sa.ForeignKeyConstraint(['device_id'], ['perangkat.device_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_sesi'], ['sesi_sholat.id_sesi'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_siswa'], ['siswa.id_siswa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_verifikator'], ['users.id_user'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status'], ['status_absensi.kode'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_absensi'),
    sa.UniqueConstraint('id_siswa', 'id_sesi', name='uq_absensi_id_siswa_id_sesi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absensi')
    op.drop_table('siswa')
    op.drop_table('sesi_sholat')
    op.drop_table('kelas')
    op.drop_table('waktu_sholat')
    op.drop_table('users')
    op.drop_table('status_absensi')
    op.drop_table('perangkat')
    # ### end Alembic commands ###
